In [ ]:
!pip install opencv-python

In [ ]:
!pip install keras

In [3]:
os.chdir('C:\\Users\\deoli\\CEN5728 - HCI')

In [ ]:
os.getcwd()

In [1]:
import os
import cv2
import time
import pyautogui

#import tensorflow as tf
from IPython.display import Image
import numpy as np
from keras.preprocessing import image
from keras.models import Sequential
from keras.models import load_model
import h5py

In [2]:
import os
import cv2
import time
import winsound

vid = cv2.VideoCapture(0, cv2.CAP_DSHOW) #Opens the inbuilt camera, trying to remove delay with second argument

window_name = "Image"
font = cv2.FONT_HERSHEY_SIMPLEX
org = (50,50)
fontScale = 1
color = (255, 0, 0)
thickness = 2


prediction = "starting"
l_call = 6
r_call = 6

path = os.getcwd()
classifier = load_model('imageClassifier10.h5')

pyautogui.FAILSAFE = False

while(True):
    
    if(l_call == 0):
        l_call = 6
        r_call = 6
        winsound.Beep(440, 500)
        pyautogui.press('left')
        #time.sleep(1)
        
    if(r_call == 0):
        r_call = 6
        l_call = 6
        winsound.Beep(440, 500)
        pyautogui.press('right')
        #time.sleep(1)
    
    ret, frame = vid.read() #Capture frame by frame
    
    frame = cv2.putText(frame, "prediction: " + prediction + " , left: " + str(l_call) + " , right: " + str(r_call) , org, font, fontScale, color, thickness, cv2.LINE_AA)
    
    cv2.imshow('Test', frame) #Display on frame
    cv2.imwrite(os.path.join(path, 'photo.jpg'), frame, [cv2.IMWRITE_JPEG_QUALITY, 9])
    #cv2.imwrite(os.path.join(path, 'photo.jpg'), frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'): #Press 'q' to stop
        break
        
    test_image = image.load_img('photo.jpg', target_size = (64, 64)) #folder predictions with images that I want to test
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
 
    result = classifier.predict(test_image) # returns array

    time.sleep(.25) 

    if(result[0][0] == 1):
        prediction = 'left' #predictions in array are in alphabetical order
        print(prediction)
        print(result)
        l_call -= 1
        #pyautogui.press('left')
        #winsound.Beep(440, 500)
        #pyautogui.PAUSE = 3
        #time.sleep(1)
    #elif (result[0][2] > result[0][0] and result[0][2] > result[0][1]):
    elif(result[0][2] == 1):
        prediction = 'right'
        print(prediction)
        print(result)
        r_call -= 1
        #3pyautogui.press('right')
        #winsound.Beep(440, 500)
        #pyautogui.PAUSE = 3
        #time.sleep(1)
    else:
        prediction = 'null'
        print(prediction)
        print(result)
        #time.sleep(1)
            
vid.release()
cv2.destroyAllWindows()

right
[[0.000000e+00 4.801901e-22 1.000000e+00]]
null
[[0. 1. 0.]]
null
[[0. 1. 0.]]
null
[[0. 1. 0.]]
null
[[0. 1. 0.]]
null
[[0. 1. 0.]]
null
[[0. 1. 0.]]
null
[[0. 1. 0.]]
left
[[1. 0. 0.]]
null
[[0. 1. 0.]]
right
[[0. 0. 1.]]
null
[[0. 1. 0.]]
left
[[1. 0. 0.]]
null
[[0. 1. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
right
[[0. 0. 1.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 0.]]
left
[[1. 0. 

In [ ]:
def print_file_size(file):
    File_Size = os.path.getsize(file)
    File_Size_MB = round(File_Size/1024/1024,2)
    
    print("Image File Size is ", str(File_Size_MB) + "MB")

print_file_size("photo.jpg")